package client.userInterface;

import javax.swing.*;
import java.awt.*;

public class pnlEditProperty {
    private JTextField txtStreet;
    private JTextField txtStreetNum;
    private JTextField txtCity;
    private JTextField txtProvince;
    private JTextField txtPostalCode;
    private JComboBox cmbQuadrant;
    private JComboBox cmbPropertyType;
    private JTextField txtBedrooms;
    private JTextField txtBathrooms;
    private JTextField txtSquareFootage;
    private JCheckBox chkFurnished;
    private JComboBox cmbPropertyStatus;
    private JButton btnSubmit;
    private JTextField txtRent;
    private JPanel pnlEditProperty;
    private JButton deletePropertyButton;

    public JTextField getTxtStreet() {
        return txtStreet;
    }

    public void setTxtStreet(JTextField txtStreet) {
        this.txtStreet = txtStreet;
    }

    public JTextField getTxtStreetNum() {
        return txtStreetNum;
    }

    public void setTxtStreetNum(JTextField txtStreetNum) {
        this.txtStreetNum = txtStreetNum;
    }

    public JTextField getTxtCity() {
        return txtCity;
    }

    public void setTxtCity(JTextField txtCity) {
        this.txtCity = txtCity;
    }

    public JTextField getTxtProvince() {
        return txtProvince;
    }

    public void setTxtProvince(JTextField txtProvince) {
        this.txtProvince = txtProvince;
    }

    public JTextField getTxtPostalCode() {
        return txtPostalCode;
    }

    public void setTxtPostalCode(JTextField txtPostalCode) {
        this.txtPostalCode = txtPostalCode;
    }

    public JComboBox getCmbQuadrant() {
        return cmbQuadrant;
    }

    public void setCmbQuadrant(JComboBox cmbQuadrant) {
        this.cmbQuadrant = cmbQuadrant;
    }

    public JComboBox getCmbPropertyType() {
        return cmbPropertyType;
    }

    public void setCmbPropertyType(JComboBox cmbPropertyType) {
        this.cmbPropertyType = cmbPropertyType;
    }

    public JTextField getTxtBedrooms() {
        return txtBedrooms;
    }

    public void setTxtBedrooms(JTextField txtBedrooms) {
        this.txtBedrooms = txtBedrooms;
    }

    public JTextField getTxtBathrooms() {
        return txtBathrooms;
    }

    public void setTxtBathrooms(JTextField txtBathrooms) {
        this.txtBathrooms = txtBathrooms;
    }

    public JTextField getTxtSquareFootage() {
        return txtSquareFootage;
    }

    public void setTxtSquareFootage(JTextField txtSquareFootage) {
        this.txtSquareFootage = txtSquareFootage;
    }

    public JCheckBox getChkFurnished() {
        return chkFurnished;
    }

    public void setChkFurnished(JCheckBox chkFurnished) {
        this.chkFurnished = chkFurnished;
    }

    public JComboBox getCmbPropertyStatus() {
        return cmbPropertyStatus;
    }

    public void setCmbPropertyStatus(JComboBox cmbPropertyStatus) {
        this.cmbPropertyStatus = cmbPropertyStatus;
    }

    public JButton getBtnSubmit() {
        return btnSubmit;
    }

    public void setBtnSubmit(JButton btnSubmit) {
        this.btnSubmit = btnSubmit;
    }

    public JTextField getTxtRent() {
        return txtRent;
    }

    public void setTxtRent(JTextField txtRent) {
        this.txtRent = txtRent;
    }

    public JPanel getPnlEditProperty() {
        return pnlEditProperty;
    }

    public void setPnlEditProperty(JPanel pnlEditProperty) {
        this.pnlEditProperty = pnlEditProperty;
    }

    public JButton getDeletePropertyButton() {
        return deletePropertyButton;
    }

    public void setDeletePropertyButton(JButton deletePropertyButton) {
        this.deletePropertyButton = deletePropertyButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlEditProperty = new JPanel();
        pnlEditProperty.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlEditProperty.add(spacer2, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Edit Property Information:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label1, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlEditProperty.add(spacer6, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Street name:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label2, gbc);
        txtStreet = new JTextField();
        txtStreet.setMinimumSize(new Dimension(120, 30));
        txtStreet.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(txtStreet, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Property Type:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label3, gbc);
        cmbPropertyType = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(cmbPropertyType, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Street Number:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label4, gbc);
        txtStreetNum = new JTextField();
        txtStreetNum.setMinimumSize(new Dimension(120, 30));
        txtStreetNum.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(txtStreetNum, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Bedrooms:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label5, gbc);
        txtBedrooms = new JTextField();
        txtBedrooms.setMinimumSize(new Dimension(120, 30));
        txtBedrooms.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(txtBedrooms, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Quadrant:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label6, gbc);
        cmbQuadrant = new JComboBox();
        cmbQuadrant.setMinimumSize(new Dimension(120, 30));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        cmbQuadrant.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(cmbQuadrant, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Bathrooms:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label7, gbc);
        txtBathrooms = new JTextField();
        txtBathrooms.setMinimumSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(txtBathrooms, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("City:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label8, gbc);
        txtCity = new JTextField();
        txtCity.setMinimumSize(new Dimension(120, 30));
        txtCity.setOpaque(false);
        txtCity.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(txtCity, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Square Footage:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label9, gbc);
        txtSquareFootage = new JTextField();
        txtSquareFootage.setMinimumSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(txtSquareFootage, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Province: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label10, gbc);
        txtProvince = new JTextField();
        txtProvince.setMinimumSize(new Dimension(120, 30));
        txtProvince.setOpaque(false);
        txtProvince.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(txtProvince, gbc);
        final JLabel label11 = new JLabel();
        label11.setText("Furnished:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label11, gbc);
        chkFurnished = new JCheckBox();
        chkFurnished.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(chkFurnished, gbc);
        final JLabel label12 = new JLabel();
        label12.setText("Postal Code:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label12, gbc);
        txtPostalCode = new JTextField();
        txtPostalCode.setMinimumSize(new Dimension(120, 30));
        txtPostalCode.setOpaque(false);
        txtPostalCode.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(txtPostalCode, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlEditProperty.add(spacer7, gbc);
        final JLabel label13 = new JLabel();
        label13.setText("Property Status:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label13, gbc);
        cmbPropertyStatus = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(cmbPropertyStatus, gbc);
        final JLabel label14 = new JLabel();
        label14.setText("Monthly Rent:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label14, gbc);
        txtRent = new JTextField();
        txtRent.setMinimumSize(new Dimension(120, 30));
        txtRent.setOpaque(false);
        txtRent.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(txtRent, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlEditProperty.add(spacer8, gbc);
        btnSubmit = new JButton();
        btnSubmit.setText("Submit");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(btnSubmit, gbc);
        deletePropertyButton = new JButton();
        deletePropertyButton.setText("Delete Property");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(deletePropertyButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlEditProperty;
    }
}
