package client.userInterface;

import entity.socket.property.Property;
import entity.socket.property.PropertyStatus;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class pnlEditProperty {

    private JLabel lblStreetNum;
    private JLabel lblCity;
    private JLabel lblProvince;
    private JLabel lblPostalCode;

    private JLabel lblBedrooms;
    private JLabel lblBathrooms;

    private JComboBox cmbPropertyStatus;
    private JButton btnUpdate;
    private JLabel lblRent;
    private JPanel pnlEditProperty;
    private JLabel lblStreetName;
    private JLabel lblQuadrant;
    private JLabel lblType;
    private JLabel lblSqrFootage;
    private JLabel lblFurnished;
    private Property property;
    private GUIController controller;

    public pnlEditProperty() {
        $$$setupUI$$$();
        btnUpdate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                property.setStatus(PropertyStatus.valueOf(cmbPropertyStatus.getSelectedItem().toString()));
                controller.updateProperty(property);
            }
        });
    }

    public void setController(GUIController controller) {
        this.controller = controller;
    }

    public void setProperty(Property property) {
        this.property = property;
    }

    public void setLabels() {
        setLblBathrooms(property.getTraits().getBathrooms() + "");
        setLblBedrooms(property.getTraits().getBedrooms() + "");
        setLblCity(property.getAddress().getCity());
        setLblFurnished(property.getTraits().getFurnished() + "");
        setLblPostalCode(property.getAddress().getPostalCode());
        setLblProvince(property.getAddress().getProvince());
        setLblQuadrant(property.getQuadrant() + "");
        setLblRent(property.getMonthlyRent() + "$");
        setLblSqrFootage(property.getTraits().getSquareFootage() + "");
        setLblStreetName(property.getAddress().getStreet());
        setLblType(property.getTraits().getType() + "");
        cmbPropertyStatus.setSelectedItem(property.getStatus());
        //TODO:Fill these Values IN, Take in an argument
    }


    public void setLblStreetNum(String newString) {
        this.lblStreetNum.setText(newString);
    }

    public void setLblCity(String newString) {
        this.lblCity.setText(newString);
    }

    public void setLblProvince(String newString) {
        this.lblProvince.setText(newString);
    }

    public void setLblPostalCode(String newString) {
        this.lblPostalCode.setText(newString);
    }

    public void setLblBedrooms(String newString) {
        this.lblBedrooms.setText(newString);
    }

    public void setLblBathrooms(String newString) {
        this.lblBathrooms.setText(newString);
    }


    public void setLblRent(String newString) {
        this.lblRent.setText(newString);
    }

    public void setLblStreetName(String newString) {
        this.lblStreetName.setText(newString);
    }

    public void setLblQuadrant(String newString) {
        this.lblQuadrant.setText(newString);
    }

    public void setLblType(String newString) {
        this.lblType.setText(newString);
    }

    public void setLblSqrFootage(String newString) {
        this.lblSqrFootage.setText(newString);
    }

    public void setLblFurnished(String newString) {
        this.lblFurnished.setText(newString);
    }

    public JPanel getPnlEditProperty() {
        return pnlEditProperty;
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlEditProperty = new JPanel();
        pnlEditProperty.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlEditProperty.add(spacer2, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Edit Property Information:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label1, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlEditProperty.add(spacer6, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Street name:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Property Type:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Street Number:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Bedrooms:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Quadrant:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Bathrooms:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label7, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("City:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label8, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("Square Footage:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label9, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Province: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label10, gbc);
        final JLabel label11 = new JLabel();
        label11.setText("Furnished:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label11, gbc);
        final JLabel label12 = new JLabel();
        label12.setText("Postal Code:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label12, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlEditProperty.add(spacer7, gbc);
        final JLabel label13 = new JLabel();
        label13.setText("Property Status:");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label13, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlEditProperty.add(spacer8, gbc);
        btnUpdate = new JButton();
        btnUpdate.setText("Update");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(btnUpdate, gbc);
        final JLabel label14 = new JLabel();
        label14.setText("Monthly Rent:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(label14, gbc);
        lblStreetName = new JLabel();
        lblStreetName.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblStreetName, gbc);
        lblStreetNum = new JLabel();
        lblStreetNum.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblStreetNum, gbc);
        lblQuadrant = new JLabel();
        lblQuadrant.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblQuadrant, gbc);
        lblCity = new JLabel();
        lblCity.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblCity, gbc);
        lblProvince = new JLabel();
        lblProvince.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblProvince, gbc);
        lblPostalCode = new JLabel();
        lblPostalCode.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblPostalCode, gbc);
        lblRent = new JLabel();
        lblRent.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblRent, gbc);
        lblType = new JLabel();
        lblType.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblType, gbc);
        lblBathrooms = new JLabel();
        lblBathrooms.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblBathrooms, gbc);
        lblSqrFootage = new JLabel();
        lblSqrFootage.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblSqrFootage, gbc);
        lblFurnished = new JLabel();
        lblFurnished.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblFurnished, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlEditProperty.add(cmbPropertyStatus, gbc);
        lblBedrooms = new JLabel();
        lblBedrooms.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        pnlEditProperty.add(lblBedrooms, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlEditProperty;
    }

    private void createUIComponents() {
        cmbPropertyStatus = new JComboBox();
        cmbPropertyStatus.addItem("AVAILABLE");
        cmbPropertyStatus.addItem("SUSPENDED");
        cmbPropertyStatus.addItem("RENTED");
        cmbPropertyStatus.addItem("REMOVED");
    }
}
