package client.userInterface;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class pnlLandlordMain {
    private JButton paymentButton;
    private JPanel pnlLandlord;
    private JButton makeNewListingButton;
    private JButton viewListingsButton;
    private GUIController controller;

    public void setController(GUIController controller) {
        this.controller = controller;
    }

    public pnlLandlordMain() {
        viewListingsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.goToLandlordProperty();
            }
        });
        paymentButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.goToPayment();
            }
        });
        makeNewListingButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.goToNewProp();
            }
        });
    }

    public JPanel getPnlLandlord() {
        return pnlLandlord;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlLandlord = new JPanel();
        pnlLandlord.setLayout(new GridBagLayout());
        paymentButton = new JButton();
        paymentButton.setText("Make Payments");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 0, 10);
        pnlLandlord.add(paymentButton, gbc);
        makeNewListingButton = new JButton();
        makeNewListingButton.setText("Make New Listing");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 0, 10);
        pnlLandlord.add(makeNewListingButton, gbc);
        viewListingsButton = new JButton();
        viewListingsButton.setText("View Listings");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 10, 0, 10);
        pnlLandlord.add(viewListingsButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlLandlord;
    }

}
