package client.userInterface;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class pnlLandordPayment {
    private JTextField txtCardNumber;
    private JTextField txtCardName;
    private JTextField txtExpirationDate;
    private JTextField txtCCV;
    private JButton submitPaymentButton;
    private JPanel pnlLandlordPayment;
    private GUIController controller;

    public pnlLandordPayment() {
        submitPaymentButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.NewLandlordPayment();
            }
        });
    }

    public void setController(GUIController controller) {
        this.controller = controller;
    }

    public JPanel getPnlLandlordPayment() {
        return pnlLandlordPayment;
    }

    public String getTxtCardNumber() {
        return txtCardNumber.getText();
    }

    public String getTxtCardName() {
        return txtCardName.getText();
    }

    public String getTxtExpirationDate() {
        return txtExpirationDate.getText();
    }

    public String getTxtCCV() {
        return txtCCV.getText();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlLandlordPayment = new JPanel();
        pnlLandlordPayment.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Enter Your Credit Card Information");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        pnlLandlordPayment.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlLandlordPayment.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlLandlordPayment.add(spacer2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Name On Card:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        pnlLandlordPayment.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Card Number");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        pnlLandlordPayment.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Expiration Date:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        pnlLandlordPayment.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("CCV:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        pnlLandlordPayment.add(label5, gbc);
        txtCardName = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlLandlordPayment.add(txtCardName, gbc);
        txtCardNumber = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlLandlordPayment.add(txtCardNumber, gbc);
        txtExpirationDate = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlLandlordPayment.add(txtExpirationDate, gbc);
        txtCCV = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlLandlordPayment.add(txtCCV, gbc);
        submitPaymentButton = new JButton();
        submitPaymentButton.setText("Submit Payment");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlLandlordPayment.add(submitPaymentButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlLandlordPayment;
    }
}
