package client.userInterface;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class pnlManagerMain {
    private JButton viewSummaryOfListingsButton;
    private JButton editAListingButton;
    private JButton viewLandlordMessagesButton;
    private JButton manageFeesButton;
    private JButton viewUsersButton;
    private JButton viewRentersButton;
    private JPanel pnlManagerMain;
    private GUIController controller;

    public void setController(GUIController controller) {
        this.controller = controller;
    }

    public pnlManagerMain() {
        viewSummaryOfListingsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.generateManagerReport();
            }
        });
        editAListingButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.viewAllProperties();
            }
        });
        viewUsersButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.goToViewUsers();
            }
        });
        manageFeesButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.goToSetFees();
            }
        });
    }

    public JButton getViewSummaryOfListingsButton() {
        return viewSummaryOfListingsButton;
    }

    public void setViewSummaryOfListingsButton(JButton viewSummaryOfListingsButton) {
        this.viewSummaryOfListingsButton = viewSummaryOfListingsButton;
    }

    public JButton getEditAListingButton() {
        return editAListingButton;
    }

    public void setEditAListingButton(JButton editAListingButton) {
        this.editAListingButton = editAListingButton;
    }

    public JButton getViewLandlordMessagesButton() {
        return viewLandlordMessagesButton;
    }

    public void setViewLandlordMessagesButton(JButton viewLandlordMessagesButton) {
        this.viewLandlordMessagesButton = viewLandlordMessagesButton;
    }

    public JButton getManageFeesButton() {
        return manageFeesButton;
    }

    public void setManageFeesButton(JButton manageFeesButton) {
        this.manageFeesButton = manageFeesButton;
    }

    public JButton getViewUsersButton() {
        return viewUsersButton;
    }

    public void setViewUsersButton(JButton viewUsersButton) {
        this.viewUsersButton = viewUsersButton;
    }

    public JButton getViewRentersButton() {
        return viewRentersButton;
    }

    public void setViewRentersButton(JButton viewRentersButton) {
        this.viewRentersButton = viewRentersButton;
    }

    public JPanel getPnlManagerMain() {
        return pnlManagerMain;
    }

    public void setPnlManagerMain(JPanel pnlManagerMain) {
        this.pnlManagerMain = pnlManagerMain;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlManagerMain = new JPanel();
        pnlManagerMain.setLayout(new GridBagLayout());
        viewSummaryOfListingsButton = new JButton();
        viewSummaryOfListingsButton.setText("View Summary of listings");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlManagerMain.add(viewSummaryOfListingsButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlManagerMain.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlManagerMain.add(spacer2, gbc);
        editAListingButton = new JButton();
        editAListingButton.setText("Edit a listing");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlManagerMain.add(editAListingButton, gbc);
        manageFeesButton = new JButton();
        manageFeesButton.setText("Manage Fees");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlManagerMain.add(manageFeesButton, gbc);
        viewUsersButton = new JButton();
        viewUsersButton.setText("View Users");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlManagerMain.add(viewUsersButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlManagerMain.add(spacer3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlManagerMain;
    }

}
