package client.userInterface;

import entity.socket.property.Property;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

public class pnlManagerReport {
    private JPanel pnlManagerReport;
    private JTable tblActiveListings;
    private JLabel txtPeriod;
    private JLabel txtNumRentedHouses;
    private JLabel txtNumHousesListed;
    private JLabel txtNumActiveListings;
    private GUIController controller;


    public void fillTable(ArrayList<Property> properties) {
//        DefaultTableModel d = (DefaultTableModel) tblResults.getModel();
//        d.setRowCount(0);
//        for (Property p : properties) {
//            String[] data = {p.getAddress().getStreetNumber() + "", p.getAddress().getStreet(),
//                    p.getQuadrant().toString(), p.getTraits().getFurnished() + "", p.getTraits().getBedrooms() + "", p.getTraits().getBathrooms() + ""};
//            d.addRow(data);
//        }
        //Todo:Make Manager Report
    }

    public void setLabels() {
//        txtNumActiveListings.setText();
//        txtNumHousesListed.setText();
//        txtNumRentedHouses.setText();
//        txtPeriod.setText();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlManagerReport = new JPanel();
        pnlManagerReport.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        pnlManagerReport.add(panel1, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("Number of Houses Rented:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        panel1.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Number of Houses Listed:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panel1.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Active Listings:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        panel1.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Summary Period");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel1.add(label4, gbc);
        txtPeriod = new JLabel();
        txtPeriod.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(txtPeriod, gbc);
        txtNumRentedHouses = new JLabel();
        txtNumRentedHouses.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(txtNumRentedHouses, gbc);
        txtNumHousesListed = new JLabel();
        txtNumHousesListed.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(txtNumHousesListed, gbc);
        txtNumActiveListings = new JLabel();
        txtNumActiveListings.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(txtNumActiveListings, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        pnlManagerReport.add(scrollPane1, BorderLayout.CENTER);
        scrollPane1.setViewportView(tblActiveListings);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlManagerReport;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
