package client.userInterface;

import javax.swing.*;
import javax.swing.text.NumberFormatter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;

public class pnlManagerFees {
    private JLabel lblCurrentFee;
    private JLabel lblCurrentPeriod;
    private JFormattedTextField txtNewFee;
    private JFormattedTextField txtNewPeriod;
    private JButton updateButton;
    private JPanel pnlManagerFees;
    private GUIController controller;

    public JPanel getPnlManagerFees() {
        return pnlManagerFees;
    }


    public pnlManagerFees() {
        $$$setupUI$$$();
        updateButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.updateFees(Integer.parseInt(getTxtNewFee()), Integer.parseInt(getTxtNewPeriod()));
            }
        });
    }

    public String getTxtNewFee() {
        return txtNewFee.getText();
    }

    public String getTxtNewPeriod() {
        return txtNewPeriod.getText();
    }


    public void setLblCurrentFee(String lblCurrentFee) {
        this.lblCurrentFee.setText(lblCurrentFee);
    }

    public void setLblCurrentPeriod(String lblCurrentPeriod) {
        this.lblCurrentPeriod.setText(lblCurrentPeriod);
    }


    public void setController(GUIController controller) {
        this.controller = controller;
    }

    private void createUIComponents() {
        NumberFormat format = NumberFormat.getInstance();
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum(Integer.MAX_VALUE);
        formatter.setAllowsInvalid(false);
        // If you want the value to be committed on each keystroke instead of focus lost
        formatter.setCommitsOnValidEdit(true);
        txtNewFee = new JFormattedTextField(formatter);
        txtNewPeriod = new JFormattedTextField(formatter);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlManagerFees = new JPanel();
        pnlManagerFees.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlManagerFees.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Current Period (Days) :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        pnlManagerFees.add(label1, gbc);
        lblCurrentPeriod = new JLabel();
        lblCurrentPeriod.setText("SETME");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        pnlManagerFees.add(lblCurrentPeriod, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("New Fee:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        pnlManagerFees.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Current Fee:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        pnlManagerFees.add(label3, gbc);
        lblCurrentFee = new JLabel();
        lblCurrentFee.setText("SETME");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        pnlManagerFees.add(lblCurrentFee, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlManagerFees.add(spacer2, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlManagerFees.add(txtNewFee, gbc);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlManagerFees.add(txtNewPeriod, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("New Period:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        pnlManagerFees.add(label4, gbc);
        updateButton = new JButton();
        updateButton.setText("Update");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlManagerFees.add(updateButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlManagerFees;
    }
}
