package client.userInterface;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class pnlRegRenterMain {
    private JButton searchPropertiesButton;
    private JButton viewSavedSearchesButton;
    private JPanel pnlRegRenterMain;
    private GUIController controller;

    public JPanel getPnlRegRenterMain() {
        return pnlRegRenterMain;
    }

    public void setController(GUIController controller) {
        this.controller = controller;
    }

    public pnlRegRenterMain() {
        searchPropertiesButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.goToRegRenterSearch();
            }
        });
        viewSavedSearchesButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.goToSavedSearches();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlRegRenterMain = new JPanel();
        pnlRegRenterMain.setLayout(new GridBagLayout());
        viewSavedSearchesButton = new JButton();
        viewSavedSearchesButton.setText("View saved searches");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRegRenterMain.add(viewSavedSearchesButton, gbc);
        searchPropertiesButton = new JButton();
        searchPropertiesButton.setText("Search Properties");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRegRenterMain.add(searchPropertiesButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlRegRenterMain;
    }
}
