package client.userInterface;

import javax.swing.*;
import java.awt.*;

public class pnlRenterSearch {
    private JTextField txtCity;
    private JComboBox cmbQuadrant;
    private JComboBox cmbPropertyType;
    private JTextField txtBedrooms;
    private JTextField txtBathrooms;
    private JTextField txtSquareFootage;
    private JCheckBox chkFurnished;
    private JTextField txtProvince;
    private JButton searchButton;
    private JTextField txtRent;
    private JComboBox cmbRentEquals;
    private JComboBox cmbFeetEquals;
    private JPanel pnlRenterSearch;
    private JComboBox cmbFurnished;
    private GUIController controller;

    public void setController(GUIController controller) {
        this.controller = controller;
    }

    public JPanel getPnlRenterSearch() {
        return pnlRenterSearch;
    }

    public void setPnlRenterSearch(JPanel pnlRenterSearch) {
        this.pnlRenterSearch = pnlRenterSearch;
    }

    public JTextField getTxtCity() {
        return txtCity;
    }

    public void setTxtCity(JTextField txtCity) {
        this.txtCity = txtCity;
    }

    public JComboBox getCmbQuadrant() {
        return cmbQuadrant;
    }

    public void setCmbQuadrant(JComboBox cmbQuadrant) {
        this.cmbQuadrant = cmbQuadrant;
    }

    public JComboBox getCmbPropertyType() {
        return cmbPropertyType;
    }

    public void setCmbPropertyType(JComboBox cmbPropertyType) {
        this.cmbPropertyType = cmbPropertyType;
    }

    public JTextField getTxtBedrooms() {
        return txtBedrooms;
    }

    public void setTxtBedrooms(JTextField txtBedrooms) {
        this.txtBedrooms = txtBedrooms;
    }

    public JTextField getTxtBathrooms() {
        return txtBathrooms;
    }

    public void setTxtBathrooms(JTextField txtBathrooms) {
        this.txtBathrooms = txtBathrooms;
    }

    public JTextField getTxtSquareFootage() {
        return txtSquareFootage;
    }

    public void setTxtSquareFootage(JTextField txtSquareFootage) {
        this.txtSquareFootage = txtSquareFootage;
    }

    public JCheckBox getChkFurnished() {
        return chkFurnished;
    }

    public void setChkFurnished(JCheckBox chkFurnished) {
        this.chkFurnished = chkFurnished;
    }

    public JTextField getTxtProvince() {
        return txtProvince;
    }

    public void setTxtProvince(JTextField txtProvince) {
        this.txtProvince = txtProvince;
    }

    public JButton getSearchButton() {
        return searchButton;
    }

    public void setSearchButton(JButton searchButton) {
        this.searchButton = searchButton;
    }

    public JTextField getTxtRent() {
        return txtRent;
    }

    public void setTxtRent(JTextField txtRent) {
        this.txtRent = txtRent;
    }

    public JComboBox getCmbRentEquals() {
        return cmbRentEquals;
    }

    public void setCmbRentEquals(JComboBox cmbRentEquals) {
        this.cmbRentEquals = cmbRentEquals;
    }

    public JComboBox getCmbFeetEquals() {
        return cmbFeetEquals;
    }

    public void setCmbFeetEquals(JComboBox cmbFeetEquals) {
        this.cmbFeetEquals = cmbFeetEquals;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlRenterSearch = new JPanel();
        pnlRenterSearch.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Search for Properties:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlRenterSearch.add(spacer1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Filter By:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Property Type:");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Bedrooms:");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Bathrooms:");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Square Footage:");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Furnished:");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label7, gbc);
        cmbPropertyType = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(cmbPropertyType, gbc);
        txtBedrooms = new JTextField();
        txtBedrooms.setMinimumSize(new Dimension(120, 30));
        txtBedrooms.setOpaque(true);
        txtBedrooms.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(txtBedrooms, gbc);
        txtBathrooms = new JTextField();
        txtBathrooms.setMinimumSize(new Dimension(120, 30));
        txtBathrooms.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(txtBathrooms, gbc);
        txtSquareFootage = new JTextField();
        txtSquareFootage.setMinimumSize(new Dimension(120, 30));
        txtSquareFootage.setOpaque(true);
        txtSquareFootage.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(txtSquareFootage, gbc);
        chkFurnished = new JCheckBox();
        chkFurnished.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 10;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(chkFurnished, gbc);
        final JLabel label8 = new JLabel();
        label8.setText("Quadrant:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label8, gbc);
        cmbQuadrant = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        cmbQuadrant.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(cmbQuadrant, gbc);
        final JLabel label9 = new JLabel();
        label9.setText("City:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label9, gbc);
        txtCity = new JTextField();
        txtCity.setMinimumSize(new Dimension(120, 30));
        txtCity.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(txtCity, gbc);
        final JLabel label10 = new JLabel();
        label10.setText("Province: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label10, gbc);
        txtProvince = new JTextField();
        txtProvince.setMinimumSize(new Dimension(120, 30));
        txtProvince.setOpaque(true);
        txtProvince.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(txtProvince, gbc);
        searchButton = new JButton();
        searchButton.setText("Search");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(searchButton, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlRenterSearch.add(spacer2, gbc);
        final JLabel label11 = new JLabel();
        label11.setText("Monthly Rent:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        pnlRenterSearch.add(label11, gbc);
        txtRent = new JTextField();
        txtRent.setMinimumSize(new Dimension(120, 30));
        txtRent.setPreferredSize(new Dimension(120, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(txtRent, gbc);
        cmbRentEquals = new JComboBox();
        cmbRentEquals.setMaximumSize(new Dimension(120, 30));
        cmbRentEquals.setMinimumSize(new Dimension(90, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(cmbRentEquals, gbc);
        cmbFeetEquals = new JComboBox();
        cmbFeetEquals.setMaximumSize(new Dimension(120, 30));
        cmbFeetEquals.setMinimumSize(new Dimension(90, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(cmbFeetEquals, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(spacer6, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlRenterSearch.add(spacer7, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlRenterSearch;
    }

}
