package client.userInterface;

import entity.socket.EmailInfo;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class pnlSendEmail {
    private JTextField txtHeader;
    private JTextField txtBody;
    private JButton sendButton;
    private JPanel pnlSendEmail;
    private GUIController controller;
    private int propID;

    public JPanel getPnlSendEmail() {
        return pnlSendEmail;
    }

    public void setController(GUIController controller) {
        this.controller = controller;
    }

    public void setPropID(int propID) {
        this.propID = propID;
    }

    public pnlSendEmail() {
        sendButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                EmailInfo ei = new EmailInfo(txtHeader.getText(), txtBody.getText());
                ei.PropertyID = propID;
                controller.SendEmail(ei);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pnlSendEmail = new JPanel();
        pnlSendEmail.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Your Email:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        pnlSendEmail.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlSendEmail.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        pnlSendEmail.add(spacer2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Message:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        pnlSendEmail.add(label2, gbc);
        txtHeader = new JTextField();
        txtHeader.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlSendEmail.add(txtHeader, gbc);
        txtBody = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlSendEmail.add(txtBody, gbc);
        sendButton = new JButton();
        sendButton.setText("Send");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pnlSendEmail.add(sendButton, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        pnlSendEmail.add(label3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlSendEmail;
    }

}
