package client.userInterface;

import entity.socket.User;
import entity.socket.property.Property;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

public class pnlViewUsers {
    private JTable tblResults;
    private JPanel pnlViewUsers;
    private GUIController controller;

    public void setController(GUIController controller) {
        this.controller = controller;
    }

    public JPanel getPnlViewUsers() {
        return pnlViewUsers;
    }

    public void fillTable(ArrayList<User> users) {
        DefaultTableModel d = (DefaultTableModel) tblResults.getModel();
        //TODO:SHOULD USE UserName and usertype,NOT Properties
        d.setRowCount(0);
        for (User u : users) {
            String[] data = {u.email, u.userType.toString()};
            d.addRow(data);
        }
        //Todo:Clear table, Add more Data
    }

    private void createUIComponents() {
        DefaultTableModel d = new DefaultTableModel();
        String[] columns = {"Username", "User type"};
        d.setColumnCount(2);
        d.setColumnIdentifiers(columns);
        tblResults = new JTable(d);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        pnlViewUsers = new JPanel();
        pnlViewUsers.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("All Users");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        pnlViewUsers.add(label1, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setMinimumSize(new Dimension(500, 300));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        pnlViewUsers.add(scrollPane1, gbc);
        scrollPane1.setViewportView(tblResults);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pnlViewUsers;
    }

}
